Repository GianniCecchetto/ChessAnywhere, pull requests merged in 2025-08, with the labels that each got.

#13 12 mise en place de la structure de fichiers du git
  .github/workflows/java-ci.yml
  .github/workflows/python-ci.yml
  .github/workflows/stm32-ci.yml
  ChessAnywhereServer/.gitignore
  ChessAnywhereServer/pom.xml
  Documentation/LandingPage/.gitkeep
  Documentation/Mockups/.gitkeep
  python-app/.gitignore
  python-app/requirements.txt
  stm32-app/.gitignore
  stm32-app/Makefile
Labels: documentation

#15 1 description du projet objectif requirements fonctionnels requirements non fonctionnels
  README.md
Labels: enhancement

#16 14 livrables semaine 1
  Livrable-sem-1/Description-arch/README.md
  Livrable-sem-1/Description-choix-technique/README.md
  Livrable-sem-1/Description-processus-de-travail/README.md
  Livrable-sem-1/Description-projet/README.md
  Livrable-sem-1/Environnement-deploiement/README.md
  Livrable-sem-1/Mockups-app-and-Landing-page/README.md
  Livrable-sem-1/Outils-dev/README.md
  Livrable-sem-1/Pipeline-livraison-et-deploiement-CI-CD/README.md
  Livrable-sem-1/README.md
Labels: enhancement

#19 description préliminaire de larchitecture
  Livrable-sem-1/Description-arch/README.md
  Livrable-sem-1/Description-arch/img/arch_projet.png
Labels: documentation

#26 24 modification livrable
  Documentation/img/Logo_ChessAnywhere.png
  Documentation/img/Logo_small.png
  Livrable-sem-1/Description-projet/README.md
  README.md
Labels: documentation

#37 ajout du bouton de creation de partie
  Livrable-sem-1/Mockups-app-and-Landing-page/README.md
  Livrable-sem-1/Mockups-app-and-Landing-page/img/mockup_app_main_v4.png
  Livrable-sem-1/Mockups-app-and-Landing-page/img/mockup_app_settings_v4.png
Labels: documentation

#39 38 implémentation des units tests stm32
  .github/workflows/stm32-ci.yml
  Documentation/stm32-self-deployment/README.md
  stm32-app/Core/Src/main.c
  stm32-app/test/test_stm32.py
Labels: documentation, enhancement, stm32

#64 Finish reading reed
  firmware/Core/Inc/bitmap.h
  firmware/Core/Src/bitmap.c
  firmware/Core/Src/main.c
  firmware/Debug/Core/Src/bitmap.cyclo
  firmware/Debug/Core/Src/bitmap.d
  firmware/Debug/Core/Src/bitmap.o
  firmware/Debug/Core/Src/bitmap.su
  firmware/Debug/Core/Src/main.cyclo
  firmware/Debug/Core/Src/main.d
  firmware/Debug/Core/Src/main.o
  firmware/Debug/Core/Src/main.su
  firmware/Debug/Core/Src/subdir.mk
  firmware/Debug/firmware.elf
  firmware/Debug/firmware.list
  firmware/Debug/firmware.map
  firmware/Debug/objects.list
Labels: stm32
